language: elixir
elixir:
  - 1.6
  - 1.7
otp_release:
  - 19.3
  - 20.3
  - 21.2
matrix:
  exclude:
    - elixir: 1.7
      otp_release: 19.3
cache:
  directories:
    - _build
    - deps
install: mix local.rebar --force; mix local.hex --force; mix deps.get
script: export MIX_ENV=test; mix test --cover; mix credo --strict
